
name: .NET Framework

on:
  push:
    branches: [ master ]
 
jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: CoreApp\CoreApp.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
    #  Test_Project_Path: TelecomColorCoder\NUnitTelecomColorCoder                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
